[package]
name = "helicase"
version = "0.1.0"
edition = "2024"
authors = ["Igor Martayan <imartayan@users.noreply.github.com>"]
description = "SIMD-accelerated parser for FASTA and FASTQ files"
keywords = ["bioinformatics", "fasta", "fastq", "parser", "simd"]
license = "MIT"

[dependencies]
ahash = "0.8.12"
bitvec = "1.0.1"
deko = { version = "0.6", default-features = false }
flate2 = { version = "1.1", features = ["zlib-rs"], optional = true }
memchr = "2.8"
memmap2 = "0.9"
packed-seq = { version = "4.4", default-features = false, optional = true }
paraseq = { version = "0.4", default-features = false, optional = true }
paste = "1.0.15"
rayon = "1.11.0"
tracing = "0.1.44"

[features]
default = ["gz", "zstd"]
bz2 = ["deko/bzip2"]
gz = ["deko/flate2", "flate2"]
xz = ["deko/xz"]
zstd = ["deko/zstd"]
no-pdep = []

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "packed"
required-features = ["packed-seq"]
