use std::fmt::{Debug, Formatter, Result as FmtResult};
use std::hash::Hash;
// Note, this is partially generated by LLM

/// Trait abstracting over the storage of bits
pub trait BitStorage: Copy + Ord + Hash + Send {
    const ZERO: Self;
    const ONE: Self;
    fn shl(&self, k: usize) -> Self;
    fn shr(&self, k: usize) -> Self;
    fn not(&self) -> Self;
    fn or(&self, other: &Self) -> Self;
    fn and(&self, other: &Self) -> Self;
    fn reverse_bits(&self) -> Self;
    fn get_bit(&self, i: usize) -> bool;
    fn set_bit(&self, i: usize, value: bool) -> Self;
    fn high_bits(&self) -> Self;
    fn low_bits(&self) -> Self;

    /// Convert to u64 for hashing purpose.
    fn fold_to_u64(&self) -> u64;

    fn first_bit_of(v: u64) -> Self;

    /// Mask to K bits
    fn mask<const K: usize>() -> Self;

    /// Get the bit width capacity of the storage
    fn bit_width() -> usize;
}

/// Implement BitStorage for primitive types
macro_rules! impl_primitive_storage {
    ($($t:ty),*) => {
        $(
            impl BitStorage for $t {
                const ZERO: $t = 0;
                const ONE: $t = 1;
                fn first_bit_of(v: u64) -> Self{
                    (v % 2) as $t
                }
                fn shl(&self, k: usize) -> Self { *self << k }
                fn shr(&self, k:usize) -> Self { *self >> k }
                fn not(&self) -> Self { !*self }
                fn or(&self, other: &Self) -> Self { self | other }
                fn and(&self, other: &Self) -> Self { self & other }
                fn reverse_bits(&self) -> Self { (*self).reverse_bits() }
                fn get_bit(&self, i: usize) -> bool { ((*self >> i) & 1) != 0 }
                fn set_bit(&self, i: usize, value: bool) -> Self {
                    (*self & !((1 as $t) << i)) | ((value as $t) << i)
                }
                fn high_bits(&self) -> Self {
                    let bw = <Self as BitStorage>::bit_width();
                    let half = bw / 2;
                    (*self >> half) & ((!0) >> (bw - half))

                }
                fn low_bits(&self) -> Self {
                    let bw = <Self as BitStorage>::bit_width();
                    let half = bw / 2;
                    *self & ((!0) >> (bw - half))
                }
                fn fold_to_u64(&self) -> u64{
                    if std::mem::size_of::<$t>() > 8 {
                        (self.high_bits() ^ self.low_bits()) as u64
                    } else {
                        *self as u64
                    }
                }
                fn bit_width() -> usize {
                    std::mem::size_of::<$t>() * 8
                }
                fn mask<const K: usize>() -> Self {
                    let bw = <Self as BitStorage>::bit_width();
                    let mask = if K >=  bw {
                        !0
                    } else {
                        (!0 >> (bw - K))
                    };
                    mask
                }
            }
        )*
    }
}

impl_primitive_storage!(u8, u16, u32, u64, u128);

/// Generic BitString wrapper
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[repr(transparent)]
pub struct BitString<T: BitStorage, const K: usize> {
    pub value: T,
}

impl<T: BitStorage, const K: usize> BitString<T, K> {
    pub const ONE: Self = BitString { value: T::ONE };
    pub const ZERO: Self = BitString { value: T::ZERO };

    /// Construct new BitString, applying K-bit mask
    #[inline(always)]
    pub fn new(value: T) -> Self {
        debug_assert!(K > 0, "BitString K must be > 0");
        debug_assert!(
            K <= T::bit_width(),
            "K should be smallel than the bitwidth ({}>{})",
            K,
            T::bit_width()
        );
        BitString {
            value: value.and(&T::mask::<K>()),
        }
    }

    #[inline(always)]
    pub fn first_bit_of(value: u64) -> Self {
        Self {
            value: T::first_bit_of(value),
        }
    }

    #[inline(always)]
    pub fn push_left<const L: usize>(&self, other: &BitString<T, L>) -> Self {
        debug_assert!(L <= K);

        // shift existing bits upward
        let shifted = self.value.shl(L);

        // other occupies the lowest L bits already
        let combined = shifted.or(other.raw());

        BitString::new(combined)
    }

    #[inline(always)]
    pub fn push_right<const L: usize>(&self, other: &BitString<T, L>) -> Self {
        debug_assert!(L <= K);

        // shift existing bits downward
        let shifted = self.value.shr(L);

        // move other into top L bits
        let top = other.raw().shl(K - L);

        let combined = shifted.or(&top);

        BitString::new(combined)
    }

    /// Bitwise not
    #[inline(always)]
    pub fn not(&self) -> Self {
        BitString::new(self.value.not())
    }

    /// Get the bit at index i
    #[inline(always)]
    pub fn get(&self, i: usize) -> bool {
        debug_assert!(i < K);
        if i >= K {
            return false;
        }
        self.value.get_bit(i)
    }

    /// Get the bitstring at position i
    #[inline(always)]
    pub fn get_bitstring<const L: usize>(&self, i: usize) -> BitString<T, L> {
        debug_assert!(
            i + L <= K,
            "slice bit exceeding the capacity {} > {}",
            i + L,
            K
        );
        BitString::<T, L>::new(self.value.shr(i))
    }

    /// Set the bit at index i
    #[inline(always)]
    pub fn set(self, i: usize, bit: bool) -> Self {
        debug_assert!(i < K);
        if i >= K {
            return self;
        }
        BitString::new(self.value.set_bit(i, bit))
    }

    /// Reverse the K-bit sequence
    #[inline(always)]
    pub fn reverse(&self) -> Self {
        let bw = T::bit_width();
        BitString::new(self.value.reverse_bits().shr(bw - K))
    }

    /// Convert to Vec<bool> (LSB at index 0)
    pub fn to_bools(&self) -> Vec<bool> {
        (0..K).map(|i| self.get(i)).collect()
    }

    /// Return the underlying storage value
    pub fn raw(&self) -> &T {
        &self.value
    }

    #[inline(always)]
    pub fn mask() -> Self {
        Self {
            value: T::mask::<K>(),
        }
    }

    /// This is extracted from https://nullprogram.com/blog/2018/07/31/
    /// and adapted to K-first bits
    pub fn hash(&self) -> u64 {
        let mut x = self.value.fold_to_u64();
        let mask = (!0) >> (64 - K);
        x ^= x >> 30;
        x *= 0xbf58476d1ce4e5b9 & mask;
        x ^= x >> 27;
        x *= 0x94d049bb133111eb & mask;
        x ^= x >> 31;
        x
    }
}

impl<T: BitStorage, const K: usize> Debug for BitString<T, K> {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        let bits: String = self
            .to_bools()
            .iter()
            .rev() // display MSB left
            .map(|b| if *b { '1' } else { '0' })
            .collect();
        write!(f, "BitString<{}>({})", K, bits)
    }
}

impl<T: BitStorage, const K: usize> From<T> for BitString<T, K> {
    fn from(value: T) -> Self {
        Self { value }
    }
}

pub fn sliding_window<T: BitStorage, const K: usize>(
    input: (&[u64], u64),
    size: usize,
) -> Vec<BitString<T, K>> {
    debug_assert!(
        size >= input.0.len() * 64,
        "size must cover all full u64 words"
    );
    let n = size - K + 1;
    let mut v = Vec::with_capacity(n);
    let mut val = BitString::<T, K>::from(T::ZERO);
    for i in 0..input.0.len() {
        let mut x = input.0[i];
        for j in 0..64 {
            val = val.push_right(&BitString::<T, 1>::first_bit_of(x));
            if 64 * i + j + 1 >= K {
                v.push(val);
            }
            x >>= 1;
        }
    }
    let rem = size - input.0.len() * 64;
    let mut x = input.1;
    debug_assert!(rem <= 64);
    for j in 0..rem {
        val = val.push_right(&BitString::<T, 1>::first_bit_of(x));
        if input.0.len() * 64 + j + 1 >= K {
            v.push(val);
        }
        x >>= 1;
    }
    assert_eq!(v.len(), n, "incorrect number of kmer computed");
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    type B5 = BitString<u8, 5>;
    type B8 = BitString<u8, 8>;
    type B16 = BitString<u16, 16>;
    type B64 = BitString<u64, 64>;

    #[test]
    fn test_masking() {
        let b: B5 = BitString::new(0b1111_1111);
        assert_eq!(*b.raw(), 0b11111);

        let b: B8 = BitString::new(0xFF);
        assert_eq!(*b.raw(), 0xFF);

        let b: B16 = BitString::new(0x1234);
        assert_eq!(*b.raw(), 0x1234);

        let b: B16 = BitString::new(0xFFFF);
        assert_eq!(*b.raw(), 0xFFFF);
    }

    #[test]
    fn test_push_left_right() {
        let b: B5 = BitString::new(0b10101);
        let b_left = b.push_left::<1>(&(1.into()));
        let expected_left = ((b.raw() << 1) & B5::mask().raw()) | 1;
        assert_eq!(*b_left.raw(), expected_left);

        let b_right = b.push_right::<1>(&(0.into()));
        let expected_right = b.raw() >> 1;
        assert_eq!(*b_right.raw(), expected_right);
    }

    #[test]
    fn test_get_set() {
        let b: B5 = BitString::new(0b10101);
        assert!(b.get(0));
        assert!(!b.get(1));
        assert!(b.get(2));

        let b2 = b.set(1, true);
        assert_eq!(*b2.raw(), 0b10111);

        let b3 = b2.set(4, false);
        assert_eq!(*b3.raw(), 0b00111);
    }

    #[test]
    fn test_not() {
        let b: B5 = BitString::new(0b10101);
        let c = b.not();
        assert_eq!(*c.raw(), 0b01010);

        let b: B8 = BitString::new(0b11001010);
        assert_eq!(*b.not().raw(), 0b00110101);
    }

    #[test]
    fn test_reverse() {
        let b: B5 = BitString::new(0b10101);
        assert_eq!(*b.reverse().raw(), 0b10101);

        let b2: B5 = BitString::new(0b11001);
        assert_eq!(*b2.reverse().raw(), 0b10011);

        let b: B8 = BitString::new(0b11001010);
        assert_eq!(*b.reverse().raw(), 0b01010011);
    }

    #[test]
    fn test_to_bools() {
        let b: B5 = BitString::new(0b10101);
        let bools = b.to_bools();
        assert_eq!(bools, vec![true, false, true, false, true]);

        let b: B8 = BitString::new(0b11001010);
        let bools: Vec<bool> = b.to_bools();
        assert_eq!(
            bools,
            vec![false, true, false, true, false, false, true, true]
        );
    }

    #[test]
    fn test_debug_display() {
        let b: B5 = BitString::new(0b10101);
        assert_eq!(format!("{:?}", b), "BitString<5>(10101)");

        let b: B8 = BitString::new(0b11001010);
        assert_eq!(format!("{:?}", b), "BitString<8>(11001010)");
    }

    #[test]
    fn test_large_bitstring_operations() {
        let b: B64 = BitString::new(0xFFFF_FFFF_FFFF_FFFF);
        let b_left = b.push_left::<1>(&(1.into()));
        let expected = ((b.raw() << 1) & B64::mask().raw()) | 1;
        assert_eq!(*b_left.raw(), expected);

        let b_right = b.push_right::<1>(&(1.into()));
        let expected = (b.raw() >> 1) | (1u64 << (63));
        assert_eq!(*b_right.raw(), expected);

        let b_right = b.push_right::<1>(&(0.into()));
        let expected = b.raw() >> 1;
        assert_eq!(*b_right.raw(), expected);

        let rev = b.reverse();
        assert_eq!(*rev.raw(), b.raw().reverse_bits());
    }
    #[test]
    fn test_push_right_semantics() {
        type B3 = BitString<u8, 3>;

        let mut v = B3::ZERO;

        v = v.push_right::<1>(&1.into()); // 1
        assert_eq!(*v.raw(), 0b100);

        v = v.push_right::<1>(&0.into()); // 1,0
        assert_eq!(*v.raw(), 0b010);

        v = v.push_right::<1>(&1.into()); // 1,0,1
        assert_eq!(*v.raw(), 0b101);
    }

    #[test]
    fn test_sliding_window_exact_fit() {
        type B3 = BitString<u8, 3>;

        // Put the bits in the remainder instead of a full u64
        // bits: 0b1101 (LSB-first: 1,0,1,1)
        let input = ([], 0b1101u64);
        let size = 4;

        let res = sliding_window::<u8, 3>((&input.0, input.1), size);

        // windows:
        // [1,0,1] = 0b101
        // [0,1,1] = 0b110
        assert_eq!(res.len(), 2);
        assert_eq!(*res[0].raw(), 0b101);
        assert_eq!(*res[1].raw(), 0b110);
    }
}
