[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
helicase = { path = "../helicase" }
clap = { version = "4.5", features = ["derive"] }
colored = "3.0"
needletail = { version = "0.6", default-features = false, features = [
    "flate2",
    "zstd",
] }
niffler = { version = "3.0", default-features = false, features = [
    "gz",
    "zstd",
] }
paraseq = { version = "0.4", default-features = false, features = ["niffler"] }
simd-minimizers = { version = "2.2", features = ["scalar"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = "0.4.8"

[features]
simd-minimizers = ["helicase/packed-seq", "dep:simd-minimizers"]

[[example]]
name = "simd_mini"
required-features = ["simd-minimizers"]
